//! AES-256-GCM encryption for face-template storage at rest.
//!
//! File format (`.enc`):
//!   [12 bytes nonce][ciphertext + 16-byte GCM tag]
//!
//! The nonce is randomly generated per write. The 16-byte GCM tag is
//! appended by `aes-gcm` automatically — any tampering with the
//! ciphertext or tag is caught on decrypt.
//!
//! Keys are 32 bytes, generated by `generate_key()` and intended to be
//! TPM-sealed via `linhello-core::seal_template_key()`.

use linhello_common::{LinuxHelloError, Result};
use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Nonce};
use rand::RngCore;
use zeroize::Zeroizing;

pub const KEY_LEN: usize = 32;
const NONCE_LEN: usize = 12;

pub fn generate_key() -> Zeroizing<Vec<u8>> {
    let mut key = Zeroizing::new(vec![0u8; KEY_LEN]);
    rand::thread_rng().fill_bytes(&mut key);
    key
}

pub fn encrypt(key: &[u8], plaintext: &[u8]) -> Result<Vec<u8>> {
    if key.len() != KEY_LEN {
        return Err(LinuxHelloError::Policy(format!(
            "template key must be {} bytes, got {}",
            KEY_LEN,
            key.len()
        )));
    }
    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| LinuxHelloError::Tpm(format!("aes init: {e}")))?;

    let mut nonce_bytes = [0u8; NONCE_LEN];
    rand::thread_rng().fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ct = cipher
        .encrypt(nonce, plaintext)
        .map_err(|e| LinuxHelloError::Tpm(format!("aes encrypt: {e}")))?;

    let mut out = Vec::with_capacity(NONCE_LEN + ct.len());
    out.extend_from_slice(&nonce_bytes);
    out.extend_from_slice(&ct);
    Ok(out)
}

pub fn decrypt(key: &[u8], blob: &[u8]) -> Result<Zeroizing<Vec<u8>>> {
    if key.len() != KEY_LEN {
        return Err(LinuxHelloError::Policy(format!(
            "template key must be {} bytes, got {}",
            KEY_LEN,
            key.len()
        )));
    }
    if blob.len() < NONCE_LEN + 16 {
        return Err(LinuxHelloError::Policy("encrypted blob too short".into()));
    }
    let (nonce_bytes, ct) = blob.split_at(NONCE_LEN);
    let nonce = Nonce::from_slice(nonce_bytes);

    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| LinuxHelloError::Tpm(format!("aes init: {e}")))?;

    let plain = cipher
        .decrypt(nonce, ct)
        .map_err(|_| LinuxHelloError::Policy("template decryption failed (wrong key or tampered data)".into()))?;
    Ok(Zeroizing::new(plain))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip() {
        let key = generate_key();
        let msg = b"hello face embeddings";
        let enc = encrypt(&key, msg).unwrap();
        let dec = decrypt(&key, &enc).unwrap();
        assert_eq!(&*dec, msg);
    }

    #[test]
    fn wrong_key_fails() {
        let key1 = generate_key();
        let key2 = generate_key();
        let enc = encrypt(&key1, b"secret").unwrap();
        assert!(decrypt(&key2, &enc).is_err());
    }

    #[test]
    fn tampered_ciphertext_fails() {
        let key = generate_key();
        let mut enc = encrypt(&key, b"secret").unwrap();
        let last = enc.len() - 1;
        enc[last] ^= 0xFF;
        assert!(decrypt(&key, &enc).is_err());
    }
}
